// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDimZuAO-dLBWjLMfuf9Ac5QfJWIQu6AP0',
    appId: '1:864519198552:web:56dae45067369f6f34372d',
    messagingSenderId: '864519198552',
    projectId: 'loginpage-37a0a',
    authDomain: 'loginpage-37a0a.firebaseapp.com',
    storageBucket: 'loginpage-37a0a.appspot.com',
    measurementId: 'G-91MEGKCF2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6470m9CEoc1MFV0tGlHbFZdYjTkLbuP0',
    appId: '1:864519198552:android:e2108e64bb607a0634372d',
    messagingSenderId: '864519198552',
    projectId: 'loginpage-37a0a',
    storageBucket: 'loginpage-37a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeTIi1jNHSuCPg_O5AjCdxLr5US1ZFlvY',
    appId: '1:864519198552:ios:ea6572ac9b1da0a534372d',
    messagingSenderId: '864519198552',
    projectId: 'loginpage-37a0a',
    storageBucket: 'loginpage-37a0a.appspot.com',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeTIi1jNHSuCPg_O5AjCdxLr5US1ZFlvY',
    appId: '1:864519198552:ios:ea6572ac9b1da0a534372d',
    messagingSenderId: '864519198552',
    projectId: 'loginpage-37a0a',
    storageBucket: 'loginpage-37a0a.appspot.com',
    iosBundleId: 'com.example.loginFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDimZuAO-dLBWjLMfuf9Ac5QfJWIQu6AP0',
    appId: '1:864519198552:web:829419f45d5855f334372d',
    messagingSenderId: '864519198552',
    projectId: 'loginpage-37a0a',
    authDomain: 'loginpage-37a0a.firebaseapp.com',
    storageBucket: 'loginpage-37a0a.appspot.com',
    measurementId: 'G-6TYRM0PSQE',
  );

}